<a href="https://colab.research.google.com/github/shreehere/MentorTasks/blob/main/Mentor_Task_Movies(MongoDB).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing MongoClient from pymongo to connect with the Database
# Importing pandas to get the result in Dataframe

from pymongo import MongoClient
import pandas as pd

In [3]:
#created a variable in the name of "Collection" to connect with MongoClient

Collection=MongoClient("mongodb://jaishree:ssunshines@ac-g9lplzi-shard-00-00.deg5rti.mongodb.net:27017,ac-g9lplzi-shard-00-01.deg5rti.mongodb.net:27017,ac-g9lplzi-shard-00-02.deg5rti.mongodb.net:27017/?ssl=true&replicaSet=atlas-10vvj7-shard-0&authSource=admin&retryWrites=true&w=majority")

In [4]:
#Adding the database "db" 

db=Collection["sample_mflix"]["movies"]

In [13]:
#Created an empty list and appending the data based on the required conditions

Result=[]
for i in db.find({'$or':[{'$and':[{'year':{'$gte':1950}},{'year':{'$lte':1970}},{"tomatoes.viewer.rating":{'$gt':3}},{"imdb.rating":{'$gt':7}},{"awards.wins":{'$gte':1}},{'genres':{'$in':["Comedy","Fantasy","Horror"]}}]},{'$and':[{'year':{'$gte':2000}},{'year':{'$lte':2015}},{"tomatoes.viewer.rating":{'$gt':3}},{"imdb.rating":{'$gt':7}},{"awards.wins":{'$gte':1}},{'genres':{'$in':["Comedy","Fantasy","Horror"]}}]}]},{"_id":0,"title":1,"directors":1,"cast":1,"imdb":1,"tomatoes":1,"awards":1,"genres":1}):
  Result.append(i)

In [14]:
# Result in the form of a Data frame
# We have got 988 rows with the conditions specified

pd.DataFrame(Result)

,genres,cast,title,directors,awards,imdb,tomatoes
0,"[Comedy, Drama, Romance]","[Judy Holliday, Broderick Crawford, William Ho...",Born Yesterday,[George Cukor],"{'wins': 5, 'nominations': 9, 'text': 'Won 1 O...","{'rating': 7.7, 'votes': 7120, 'id': 42276}","{'viewer': {'rating': 3.9, 'numReviews': 4650,..."
1,"[Animation, Family, Fantasy]","[Ilene Woods, Eleanor Audley, Verna Felton, Cl...",Cinderella,"[Clyde Geronimi, Wilfred Jackson, Hamilton Luske]","{'wins': 7, 'nominations': 4, 'text': 'Nominat...","{'rating': 7.3, 'votes': 93731, 'id': 42332}","{'viewer': {'rating': 3.5, 'numReviews': 86076..."
2,"[Family, Comedy]","[Antje Weisgerber, Peter Mosbacher, Jutta Gènt...",Das doppelte Lottchen,[Josef von Bèky],"{'wins': 3, 'nominations': 1, 'text': '3 wins ...","{'rating': 7.1, 'votes': 329, 'id': 42409}","{'viewer': {'rating': 3.5, 'numReviews': 3}, '..."
3,"[Comedy, Drama]","[James Stewart, Josephine Hull, Peggy Dow, Cha...",Harvey,[Henry Koster],"{'wins': 2, 'nominations': 4, 'text': 'Won 1 O...","{'rating': 8.1, 'votes': 42373, 'id': 42546}","{'viewer': {'rating': 4.0, 'numReviews': 38164..."
4,"[Comedy, Crime]","[Burt Lancaster, Dorothy McGuire, Edmund Gwenn...",Mister 880,[Edmund Goulding],"{'wins': 3, 'nominations': 0, 'text': 'Nominat...","{'rating': 7.2, 'votes': 765, 'id': 42742}","{'viewer': {'rating': 3.3, 'numReviews': 106, ..."
...,...,...,...,...,...,...,...
983,"[Documentary, Comedy, Drama]","[Seija Airamo, Erkki Broman, Pirjo Mutanen, Ma...",Garden Lovers,[Virpi Suutari],"{'wins': 5, 'nominations': 3, 'text': '5 wins ...","{'rating': 7.3, 'votes': 80, 'id': 3105418}","{'viewer': {'rating': 3.8, 'numReviews': 3}, '..."
984,[Comedy],"[Maz Jobrani, John Heard, Deanna Russo, Marsha...",Jimmy Vestvood: Amerikan Hero,[Jonathan Kesselman],"{'wins': 2, 'nominations': 0, 'text': '2 wins.'}","{'rating': 8.2, 'votes': 48, 'id': 3135556}","{'viewer': {'rating': 3.5, 'numReviews': 42}, ..."
985,"[Comedy, Drama]","[Asa Butterfield, Rafe Spall, Sally Hawkins, E...",A Brilliant Young Mind,[Morgan Matthews],"{'wins': 3, 'nominations': 6, 'text': '3 wins ...","{'rating': 7.2, 'votes': 7960, 'id': 3149038}","{'website': 'http://www.xplusymovie.com/', 'vi..."
986,"[Comedy, Drama]","[Garrett M. Brown, Rachel DiPillo, Mary Kate W...","Hello, My Name Is Frank",[Dale Peterson],"{'wins': 4, 'nominations': 1, 'text': '4 wins ...","{'rating': 8.3, 'votes': 24, 'id': 3163080}","{'viewer': {'rating': 5.0, 'numReviews': 5}, '..."
987,"[Comedy, Drama]","[Ze'ev Revach, Levana Finkelstein, Aliza Rosen...",The Farewell Party,"[Tal Granit, Sharon Maymon]","{'wins': 9, 'nominations': 11, 'text': '9 wins...","{'rating': 7.2, 'votes': 626, 'id': 3163304}",{'website': 'http://www.2teamproductions.com/e...